# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [2]:
# Create the following numpy array
import numpy as np
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
x = np.arange(0,10,1)
x * 2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [2]:
# Perform adding operations (add the array in itself)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
x * x

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [3]:
# Perform multiplication operations (multiply the array with itself)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
x - x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
# Perform subtraction operations (subtract the array with itself)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
x / x

C:\Users\delchain_default\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [5]:
# Divide the array with itself

# YOU WILL NOTICE!
# Warning on division by zero, but not an error!
# Just replaced with nan

/Users/marci/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [9]:
x **3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [10]:
# Recreate the following array (arr[i]^3)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [10]:
x ** 0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [12]:
#Taking Square Roots

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [16]:

np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [13]:
#Calcualting exponential (e^)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [20]:
max_x = np.max(x,axis=0)
print(max_x)

x.max()

9


9

In [14]:
#same as arr.max()

9

In [21]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [15]:
# Calculate the sin of array elements

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [22]:
np.log(x)

C:\Users\delchain_default\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [16]:
# Calculate the log of array elements

/Users/marci/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458])

# Great Job!

That's all we need to know for now!