# LESSON 6 - 27apr20 - NUMPY

### Basics

In [1]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# Print arrays dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3



Access Array Elements
- 1 dimensions array: indexing is the same as accessing an array element
- higer dimensions array: same as for indexing

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr[0])
print(arr[0]+arr[1])

1
3


In [3]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


Slicing Arrays
- Slicing in python means taking elements from one given index to another given index.
- We pass slice instead of index like this: [start:end].
- We can also define the step, like this: [start:end:step].

Notes
- If we don't pass start its considered 0
- If we don't pass end its considered length of array in that dimension
- If we don't pass step its considered 1

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [5]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]



Data Types

Python
- string
- integer
- float
- bolean
- complex

Numpy
- i integer
- b bolean
- u unsigned integer
- f float
- c complex float
- m timedelta
- M datetime
- O object
- S string
- U unicode string
- V fixed chunk of memory for other type (void)

In [7]:
# To create an array with a defined type:

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [8]:
# Create an array with data type 4 bytes integer:

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [9]:
# convert arry type

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


Copy vs View
- The copy owns the data and 
    - any changes made to the copy will not affect original array
     - any changes made to the original array will not affect the copy.

- The view does not own the data and 
    - any changes made to the view will affect the original array
    - any changes made to the original array will affect the view.

In [10]:
# Make a copy, change the original array, and display both arrays:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [11]:
#Make a view, change the original array, then change the view array. print all:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

print('-'*25)

x[0]= 31
print(x)
print(arr)

[42  2  3  4  5]
[42  2  3  4  5]
-------------------------
[31  2  3  4  5]
[31  2  3  4  5]


### Arange


NumPy arange() creates an instance of ndarray with evenly spaced values and returns the reference to it.
You can define 
- interval of the values contained in an array
- space between them,
- their type 

numpy.arange([start, ]stop, [step, ], dtype=None) 
- start is the number (integer or decimal) that defines the first value in the array.
- stop is the number that defines the end of the array and isn’t included in the array.
- step is the number that defines the spacing (difference) between each two consecutive values in the array - default = 1.
- dtype is the type of the elements of the output array and defaults to None.

In [12]:
np.arange(1, 10, 3)

array([1, 4, 7])

In [13]:
a = np.zeros(3)
b = np.zeros((5,5))
c = np.ones((3,3))
d = np.repeat(3, 10)
e = np.full(10, 3)


print(a)
print(b)
print(c)
print(d)
print(e)

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[3 3 3 3 3 3 3 3 3 3]
[3 3 3 3 3 3 3 3 3 3]


### Linspace


Linspace Used to generate a linear sequence out of the range of numbers provided

numpy.linspace(start, stop, num , endpoint , retstep , dtype) :
- start : start of interval range. Default = 0
- stop : end of interval range
- num : No. of samples to generate [int, optional] 
- endpoint: True/False
- restep : If True, return (samples, step). Default = False
- dtype : type of output array. 

In [15]:
np.linspace(1, 3, 5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [61]:
np.linspace(0,1,20)        #array from 0 to 1, 20 equally spaced

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Eye

Eye returns a 2-D array with ones on the diagonal and zeros elsewhere.

np.eye(N, M, k=0, dtype, order)
- N : number of rows.
- M : number of columns - optional. Default M(number of columns) = N(Number of Rows)
- k : Diagonal. - optional By default k=0. (k>0) refers to an upper diagonal, (k<0) is a lower diagonal.
- dtype : data type - optional. Default = float.
- order : The order parameter can be either C_contiguous or F_contiguous (DEfault = C)

In [16]:
np.eye(4, 4, k = 0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random

In [18]:
a = np.random.randint(0,100,10)
b = np.random.randint(0,100,(3,4))

print(a)
print("\n")
print(b)

[34 66 50 35 78  3 68 13 97 62]


[[98  6 59 24]
 [76  5  0 17]
 [49 66 93 69]]


In [19]:
c = np.random.randn(1)
d = np.random.randn(25)

print(c)
print("\n")
print(d)

[2.2941068]


[-0.39411097  0.39075955 -1.84179154 -1.14983149  2.15633155  0.23440741
 -0.90404454 -0.7957484   0.4681399   0.75219554  0.71154575  0.02581863
 -0.54925956  0.5554448   0.45028178 -0.19223971  1.34163625  0.42943949
 -0.9143807   0.00743165  0.72431857  0.58121066 -0.79028961  0.63816738
 -0.50733942]


### Shape / Re-Shape


Shape: Returns a tuple with each index having the number of corresponding elements.

Reminder: (very useful for looping)
1st element: rows
2nd element: Columns


In [20]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)



Reshape: changing the shape of an array. The shape of an array is the number of elements in each dimension. By reshaping we can add or remove dimensions or change number of elements in each dimension

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Putting it all together

In [23]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
#looping through each element

rows = mat.shape[0]
cols = mat.shape[1]

for x in range(0, rows):
    for y in range(0, cols):
        print(mat[x,y])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25


In [26]:
# total of the matrce

rows = mat.shape[0]
cols = mat.shape[1]
total = 0

for i in range(rows):
    for j in range (cols):
        total += mat[i,j]
total

325

### Iterating - lvl 1


It is possible to loop through arrays with loops. Multiple dimensions are dealt with nested loops

In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [28]:
total =0
i = 0

for i in mat:
    total += i

total

array([55, 60, 65, 70, 75])

### Join

Joining means putting contents of two or more arrays in a single array.

In [29]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [35]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)
print(arr)

print("-"*25)

arrrr = np.concatenate((arr1, arr2), axis=1)
print(arrrr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
-------------------------
[[1 2 5 6]
 [3 4 7 8]]


### Split


Splitting is reverse operation of Joining. 

Joining merges multiple arrays into one and Splitting breaks one array into multiple. If the array has less elements than required, it will adjust from the end accordingly.

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### Search



You can search an array for a certain value, and return the indexes that get a match.

In [37]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [38]:
# find even numbers

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


### Sort


Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

In [39]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


### Filter


Filter based on bolean values

In [40]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


### Ufunc


funcs stands for "Universal Functions" and they are NumPy functions that operates on the ndarray object.

https://www.w3schools.com/python/numpy_ufunc.asp

In [42]:
# without ufunc, with zip:
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[5, 7, 9, 11]


In [43]:
# same thing, using ufunc add(x,y) 


x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


### max,min,argmax,argmin



Argmax: used to get the indices of the maximum element from an array (single-dimensional array) or any row or column (multidimensional array) of any given array.

argmax(array, axis , out ) 
- array : Input array to work on 
- axis  : Along a specified axis like 0 or 1 - [int, optional]
- out   : Provides a feature to insert output to the out array and it should be of appropriate shape and dtype [array optional]

In [44]:
import numpy as np

a = np.random.randint(0,100,10)
b = np.argmax(a,axis=0)

print(a)
print(b)

[73 11 14  8 97 28 61 69 26  6]
4


# LESSON 7 - 29apr20 - NUMPY


### Broadcasting



The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. 
- Arithmetic operations on arrays are usually done on corresponding elements. 
- If two arrays are of exactly the same shape, then these operations are smoothly performed.

In [45]:
a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

[ 10  40  90 160]


If the dimensions of two arrays are dissimilar, element-to-element operations are not possible. 
- However, operations on arrays of non-similar shapes is still possible in NumPy, because of the broadcasting capability. 
- The smaller array is broadcast to the size of the larger array so that they have compatible shapes.

Broadcasting is possible if the following rules are satisfied −
- Array with smaller ndim than the other is prepended with '1' in its shape.
- Size in each dimension of the output shape is maximum of the input sizes in that dimension.
- An input can be used in calculation, if its size in a particular dimension matches the output size or its value is exactly 1.
- If an input has a dimension size of 1, the first data entry in that dimension is used for all calculations along that dimension.

A set of arrays is said to be broadcastable if the above rules produce a valid result and one of the following is true −
- Arrays have exactly the same shape.
- Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.
- Array having too few dimensions can have its shape prepended with a dimension of length 1, so that the above stated property is true.

In [46]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print('First array:')
print(a)
print('\n')
   
print('Second array:')
print(b) 
print('\n')  
   
print('First Array + Second Array')
print(a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [47]:
print(a * b)

[[ 0.  0.  0.]
 [10. 20. 30.]
 [20. 40. 60.]
 [30. 60. 90.]]


### Iterating lvl 2


NumPy package contains an iterator object numpy.nditer. 
- It is an efficient multidimensional iterator object using which it is possible to iterate over an array. 
- Each element of an array is visited using Python’s standard Iterator interface.

In [48]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print ('Original array is:')
print (a)
print ('\n')

print ('Modified array is:')
for x in np.nditer(a):
   print(x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


### Slicing - lvl1


- We pass slice instead of index like this: [start:end]
- We can also define the step, like this: [start:end:step]

In [49]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])       #start at 1, finish at 5, in 2 steps

[2 4]


### 2D Matrices - Example 1

In [50]:
w = np.array(np.arange(5,85,5))
x = np.reshape(w, (4,4))
x

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60],
       [65, 70, 75, 80]])

### Slicing lvl2 - on a 2D matrice

In [51]:
#isolate upper right 2 x 2 
x[0:2,-2:4] 

array([[15, 20],
       [35, 40]])

In [52]:
# This is the same thing as just above
x[:2,2:]

array([[15, 20],
       [35, 40]])

In [53]:
#isolate lower right 2 x 2 
x[2:4,-2:4] 

array([[55, 60],
       [75, 80]])

In [54]:
# This is the same thing as just above
x[2:,2:]

array([[55, 60],
       [75, 80]])

In [55]:
x[0][2]

15

In [56]:
x[[1,3]]


array([[25, 30, 35, 40],
       [65, 70, 75, 80]])

In [57]:
x[:,[0,2]]

array([[ 5, 15],
       [25, 35],
       [45, 55],
       [65, 75]])

### 2D Matrices - Example 2

In [58]:
#create a matrice of zeroes
b = np.zeros((10,10))
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [59]:
#Using for loop to change values
i = 0

for i in range(0,10):
   b[i:] = i
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [60]:
#Filter even numbers
filter_b = b[:,0]%2 == 0   #filter on 1st column, all rows

new_b = b[filter_b]
new_b



array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

### 2D Matrices - Example 3


In [62]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
x = np.arange(12,27,1).reshape(3,5)
x[:3,:4]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [64]:
x[2,:]-1

array([21, 22, 23, 24, 25])

In [65]:
np.sum(mat)

325

In [66]:
np.std(mat)

7.211102550927978

In [70]:
#sum of all columns
mat.sum(axis=0)


array([55, 60, 65, 70, 75])

In [71]:
#sum of all lines
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])