# Learning Notes 6 - Pandas 4

## Split Train Test

We have two datasets.

* One has independent features, called (x).


* One has dependent variables, called (y).

To split it, we do:

* x Train – x Test / y Train – y Test

Then

* x Train and y Train become data for the machine learning, capable to create a model. 

* Once the model is created, input x Test and the output should be equal to y Test. 

* The more closely the model output is to y Test: the more accurate the model is.

In [5]:
# Example

import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
list(y)

[0, 1, 2, 3, 4]

In [7]:
# Then split, lets take 33% for testing set (whats left for training).

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [8]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [9]:
X_test

array([[2, 3],
       [8, 9]])

In [10]:
y_train

[2, 0, 3]

In [11]:
y_test

[1, 4]

In [ ]:
# Example

import numpy as np
import sklearn
 
X = df1['Households_log']
y = df1['RPI_log']  

X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, train_size=0.75,test_size=0.25)
print ("X_train: ", X_train)
print ("y_train: ", y_train)
print("X_test: ", X_test)
print ("y_test: ", y_test)

In [ ]:
import numpy as np
import sklearn

X = df1.iloc[:,2:176]
y = df1['RPI_log']

X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, train_size=0.75,test_size=0.25)

## Label Encoding

Label encoding: transform strings into numbers

 Since machines can only process numbers, we need to convert an index into a numerical value

In [ ]:
There is a built-in function for that: 
    
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 

df1['Quarter']= label_encoder.fit_transform(df1['Quarter']) 
df1['Quarter'].unique() 
