# Composition and NumPy

    Dated: April 24, 2020

# Useful resources


## Note:
### Before moving on to Numpy:
    I want to tell you that Numpy is a very vast topic, just like OOP. We can spend a month and that won't be enough, so what we will do is, we will code the basics first, things that I believe are important and will be required in this course. And with time, if you have to do something you've never done before with Numpy. You'll be able to go through the documentation and find your answers. There is every solution to every problem on internet. 
    
    So what my point is, you won't be able to memorize all the syntax and function calls. You'll always have to check the internet or the official documentation of Numpy, which is very well written. 

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Question 1 - Create NumPy Arrays

### From a Python List

    Create a Python list and convert it into a Numpy array

In [3]:
# Your code goes here

import numpy as np

a = list(range(1,11))
b = np.array(a)
print(b)


[ 1  2  3  4  5  6  7  8  9 10]


## Question 2: Using 'arange()' of Numpy - 

Return evenly spaced values within a given interval.

In [10]:
# Recreate the sample outputs
# your code goes here
np.arange(start=0, stop=10, step=1)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# Sample output 1
np.arange(0, 10, 1)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Sample output 2

np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

## Question 3: Create matrices/arrays of zeros and ones

Generate arrays of zeros or ones

In [17]:
# Your code goes here
# recreate the sample outputs

np.zeros(3)



array([0., 0., 0.])

In [11]:
# Sample output 1

array([0., 0., 0.])

In [19]:
# Sample output 2

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
# Sample output 3

np.ones(3)

array([1., 1., 1.])

In [21]:
# Sample output 4

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Question 4: Using linspace()
Return evenly spaced numbers over a specified interval.

In [23]:
# your code goes here
# Recreate the sample outputs

np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [17]:
# sample output 1

array([ 0.,  5., 10.])

In [24]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [18]:
# sample output 2

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Question 5: Using eye()
Create an identity matrix

In [27]:
# your code goes here
# Recreate the sample output

np.eye(4, 4, k = 0)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# Sample output

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Composition

## Question 6:
Create three classes Car, Engine, Owner

Now identify the relationships here and answer below.

Note: Give any attributes of your choice to the classes. For example: Car -> car_make, model
Main thing is how you deal with the relationship! 

In [43]:
class Car():
    def __init__(self, Brand, Model, Year, Engine):
        self.Brand = Brand
        self.Model = Model
        self.Year = Year
        self.Engine = Engine

In [57]:
class Engine():
    def __init__(self,Engine_type):
        self.Engine_type = Engine_type
        
    def __str__(self):
        return "My Engine is a {}".format(self.Engine_type)

In [113]:
class Owner():
    
    def __init__(self, Name, Car):
        self.Name = Name
        self.Car = Car
        
    def __str__(self):
        return "My Name is {}".format(self.Name)
    
    def intro(self):
        return "I am the owner of a {}{}, with a {} Engine".format(self.Car.Brand, self.Car.Year, self.Engine)

In [118]:
# Driver code goes here

Driver = Owner("Ricky",My_Car)
My_Car = Car("Toyota", "Corolla", 1984, My_Engine)
My_Engine = Engine("Turbo Injection")

#standard
print(My_Engine)
print(Driver.Name)
print(My_Car.Year)

#composition
print ('-'*30)
print(My_Car.Engine)       # this is ok
print(Driver.Car.Engine)   # this is ok

#composition
print ('-'*30)
print(Driver.Owner.intro)         # this is NOK


# failed
print ('-'*30)
#print(Owner)              # i do not understand why it does not work
#print(Owner.Car.Engine)   # this is NOK - has no attribute Car





My Engine is a Turbo Injection
Ricky
1984
------------------------------
My Engine is a Turbo Injection
My Engine is a Turbo Injection
------------------------------


AttributeError: 'Owner' object has no attribute 'Owner'

In [95]:
Driver = Owner("Ricky","My_2nd_Car")
My_2nd_Car = Car("Toyota", "Corolla", 1984, My_2nd_Engine)
My_2nd_Engine = Engine("Banana")


print(My_2nd_Car.Engine)   # Could I expect " Banana as an output" ? 
print(My_2nd_Engine)       

My Engine is a Banana
My Engine is a Banana


# Best of luck
**We are all in the gutter, but some of us are looking at the stars!**