# NumPy Indexing and Selection

In this exercise we will focus on how to select elements or groups of elements from an array.

### Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [18]:
# Create the following

import numpy as np

arr = np.arange(0,12,1)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
# Using arange


In [19]:
arr[3]

3

In [3]:
# Selecting an element

3

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [6]:
#Get values in a range

array([0, 1, 2, 3, 4])

In [20]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
#Get values in a range

array([1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [22]:
x = arr.view()
x[0:5] = 100
x



array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11])

In [8]:
#Setting a value with index range (Broadcasting)


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11])

In [23]:
x = np.arange(0,12,1)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
# Reset array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
x[0:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
#Slice the array

#Show slice


array([0, 1, 2, 3, 4, 5])

I am not sure about the below - did you wanted to copy or view the initial array, bring modifications in order to see the modifications to original array? (in this case, view)

In [28]:
x = arr.view()
x[0:6] = 99
x[0:6]


array([99, 99, 99, 99, 99, 99])

In [11]:
#Change Slice
#Show Slice again

array([99, 99, 99, 99, 99, 99])

In [12]:
# Now note the changes also occur in our original array!

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11])

In [13]:
# Original array changed as well

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Use copy() to get a copy of above array

In [30]:
y = arr.copy()
y

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11])

In [14]:
# Copy of array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [37]:
arr_2d = np.array([np.arange(5,20,5),np.arange(20,35,5)])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30]])

In [155]:
w = np.array(np.arange(5,50,5))
t = np.reshape(w, (3,3))
print(t.ndim)



2


In [15]:
# Create a 2-D matrix

#Show


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [39]:
arr_2d[1]

array([20, 25, 30])

In [16]:
# Print the second row

array([20, 25, 30])

In [40]:
arr_2d[1][0]

20

In [17]:
# Getting individual element value

20

In [49]:
arr_2d[1,0]

20

In [18]:
# Getting individual element value using comma notaion

20

In [96]:
arr_2d[0:2,-2:3]   # that is not super intuitive

array([[10, 15],
       [25, 30]])

In [154]:
arr_2d[:2,1:]   # that is not super intuitive

array([[10, 15],
       [25, 30]])

In [76]:
# 2D array slicing

#Shape (2,2) from top right corner

In [100]:
a = np.arange(5,50,5)
z = np.reshape(a, (3,3))
z




array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [104]:
z[2]

array([35, 40, 45])

In [21]:
#Shape bottom row

array([35, 40, 45])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [108]:
b = np.zeros((10,10))
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
#Set up matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [109]:
len(b)

10

In [24]:
#Length of array

10

In [126]:
i = 0

for i in range(0,10):
   b[i:] = i

b


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [25]:
#Set up array
#Loop through the array and set the value of index = i

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [129]:


filter_b = b % 2 == 0

new_b = b[filter_b]
new_b



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 6., 6., 6., 6.,
       6., 6., 6., 6., 6., 6., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.])

In [130]:
filter_b = b[:,0]%2 == 0

new_b = b[filter_b]
new_b


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [26]:
# Extract

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [145]:
import random

b = []

for i in range (0,4):
    a = random.randint(1,10)
    np_array_1d = np.array([a])
    b.append(np_array_1d)
    
c = np.repeat(b,10,1)
c



array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [27]:
#Allows in any order

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

# Good luck!
Try doing OOP exercises on your own, ping me if you face any problems.