## Exercise 9 - NumPy Basics
Read randn, rand, reshape, max,min,argmax,argmin before attempting this exercise


# Question 1 - Using randn
Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [5]:
# Your code goes here
# Create the following outputs - Your output values may differ.
import numpy as np
import random

np.random.randn(2)


array([0.32727288, 0.24674772])

In [2]:
# Sample output 1 

array([0.74677682, 0.24891535])

In [6]:
np.random.randn(25)

array([ 0.30770954, -0.26929322,  0.38508624, -0.87254534,  0.53175764,
        0.69527271,  0.73070337,  0.84358208, -0.21431376,  2.1799973 ,
       -0.13557411,  0.11509193,  0.16008106,  0.51797226, -0.80211989,
       -1.15280793,  0.30524201,  0.08066972, -0.60352291,  0.21186362,
        0.17841302, -0.62280981, -0.43847052, -2.12108148,  0.08635456])

In [3]:
# Sample output 2

array([[-0.83945047, -1.041149  , -0.92783957, -0.77700242,  1.79558298],
       [ 0.31362323,  1.47329718, -0.88272931, -0.14955721,  1.72843409],
       [-0.92024778, -0.10572301,  0.27749848, -2.33204229, -2.01664889],
       [-0.54651944,  0.00540425, -1.92782217,  0.44669671,  2.42135002],
       [-0.28597671,  0.6230888 ,  2.78732082,  0.21284029,  1.10940165]])

# Question 2 - Using randint
Return random integers from low (inclusive) to high (exclusive).

In [7]:
# Your code goes here
# Create the following outputs - Your output values may differ.

np.random.randint(0,100)


29

In [5]:
# Sample output 1 

44

In [9]:
np.random.randint(0,100,10)

array([48, 16, 45, 44, 68, 28, 45, 42, 76, 21])

In [10]:
np.random.randint(0,100,(3,4))

array([[84, 11, 30, 13],
       [46, 24, 49, 12],
       [ 0, 51, 92, 68]])

In [6]:
# Sample output 2

array([10, 97, 49, 30, 58, 75, 96, 18,  2,  7])

# Question 3 - Let's discuss some useful attributes and methods
    Step 1 - Create an array using arange()
    Step 2 - Reshape the array using reshape() method 

In [13]:
# Your code goes here

np.arange(start=0, stop=25, step=1)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
# Question: why a comes out differently? (no comas)

a = np.arange(start=0, stop=25, step=1)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [8]:
# Step 1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
b = np.arange(start=0, stop=25, step=1)
b.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
# Step 2 - Reshape in 5 x 5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin
These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [22]:
# Use each method on the array create above

a = np.random.randint(0,100,10)

max_a = np.max(a,axis=0)
min_a = np.min(a,axis=0)
argmax = np.argmax(a,axis=0)
argmin = np.argmin(a,axis=0)

print(a)

print(max_a)
print(min_a)
print(argmax)
print(argmin)

[51 57 79 90 75 65  1 26 12 43]
90
1
3
6


# Good luck and Happy coding!